model:
  # relative path (portable across systems)
  path: "model_sharable"

  # task type (sentiment, text-classification, etc.)
  task: "sentiment-analysis"

  # "cpu" or "cuda:0" for GPU
  device: "cpu"

  # Hugging Face Hub model id
  hub_id: "distilbert/distilbert-base-uncased-finetuned-sst-2-english"

logging:
  # DEBUG, INFO, WARNING, ERROR
  level: "INFO"

  # set true if you want logs written to a file
  save_logs: false

data:
  # default input for quick tests
  sample_input: "MLOps is amazing!"

  # useful if later you want batched inference
  batch_size: 1
